M48
; DRILL file {KiCad (7.0.0)} date Fri Apr 21 02:07:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-21T02:07:04-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X2.3681Y-2.8583
X2.3681Y-3.0315
T2
X2.3848Y-2.1378
X2.3848Y-3.5551
X5.5541Y-2.1575
X5.5541Y-3.5551
T0
M30
